/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemafutbol;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author H ERICK
 */
public class frmarbitros_partidos extends javax.swing.JFrame {

    ResultSet rs = null;
    arbitros_partidos ac = new arbitros_partidos(); 
    boolean registro = false;
    boolean prueba = false;
    boolean newRecord = false;
    int cantidad = 0;
    int mayor = 0;
    public frmarbitros_partidos() {
        initComponents();
        txtregistro.setEnabled(false);
        txtidarbitro.setEnabled(false);
        txtidpartido.setEnabled(false);
        txtpuesto.setEnabled(false);
        
    }
    private void Bloquear(){
        txtregistro.setEnabled(false);
        txtidarbitro.setEnabled(false);
        txtidpartido.setEnabled(false);
        txtpuesto.setEnabled(false);
        }
        
        private void Desbloquear() {
       txtidarbitro.setEnabled(true);
       txtidpartido.setEnabled(true);
       txtpuesto.setEnabled(true);
       }
        
        private void Limpiar() {
       txtidarbitro.setText("");
       txtidpartido.setText("");
       txtpuesto.setText("");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblregistro = new javax.swing.JLabel();
        txtregistro = new javax.swing.JTextField();
        lblidarbitro = new javax.swing.JLabel();
        txtidarbitro = new javax.swing.JTextField();
        lblidpartido = new javax.swing.JLabel();
        txtidpartido = new javax.swing.JTextField();
        lblpuesto = new javax.swing.JLabel();
        txtpuesto = new javax.swing.JTextField();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnguardarmodificacion = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ARBITROS_PARTIDOS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblregistro.setText("REGISTRO:");
        getContentPane().add(lblregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        getContentPane().add(txtregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, -1));

        lblidarbitro.setText("ID ARBITRO:");
        getContentPane().add(lblidarbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtidarbitro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidarbitroKeyTyped(evt);
            }
        });
        getContentPane().add(txtidarbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 130, -1));

        lblidpartido.setText("ID PARTIDO:");
        getContentPane().add(lblidpartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));

        txtidpartido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidpartidoKeyTyped(evt);
            }
        });
        getContentPane().add(txtidpartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 130, -1));

        lblpuesto.setText("PUESTO:");
        getContentPane().add(lblpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtpuesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpuestoKeyTyped(evt);
            }
        });
        getContentPane().add(txtpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 190, -1));

        btnnuevo.setText("NUEVO");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, -1));

        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        btnbuscar.setText("BUSCAR");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, -1));

        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        btnmodificar.setText("MODIFICAR");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        btnguardarmodificacion.setText("GUARDAR MODIFICACIÓN");
        btnguardarmodificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarmodificacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardarmodificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 190, -1));

        btncancelar.setText("CANCELAR");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed

        // TODO add your handling code here:
        rs = null;
        //mÃ©todo en clase Clientes
        rs = ac.contarRegistros();
        try {
            while (rs.next()) {
                cantidad = rs.getInt(1);
                if (cantidad != 0) {
                    rs = null;
                    //mÃ©todo en clase Clientes
                    rs = ac.mayorRegistro();
                    while (rs.next()) {
                        mayor = rs.getInt(1) + 1;
                        //recuerde que debe completar 5 digitos
                        if (mayor < 10) {
                            txtregistro.setText("0000" + mayor);
                        } else if (mayor < 100) {
                            this.txtregistro.setText("000" + mayor);
                        } else if (mayor < 1000) {
                            txtregistro.setText("00" + mayor);
                        } else if (mayor < 10000) {
                            txtregistro.setText("0" + mayor);
                        } else {
                            txtregistro.setText("" + mayor);
                        }
                    }
                } else {
                    txtregistro.setText("0000"+1);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "AVISO DEL SISTEMA", 0);
        }
        Desbloquear();
        Limpiar();
        this.txtidarbitro.requestFocus();
        newRecord = true;
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed

        if (newRecord == true) {
            if (this.txtregistro.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe existir un numero de registro", "AVISO DEL SISTEMA", 2);
            } else if (this.txtidarbitro.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe llenar el campo ID ARBITRO", "AVISO DEL SISTEMA", 2);
                this.txtidarbitro.requestFocus();
            }else if (this.txtidpartido.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe llenar el campo ID PARTIDO", "AVISO DEL SISTEMA", 2);
                this.txtidpartido.requestFocus();
            } else if (this.txtpuesto.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe llenar el campo PUESTO", "AVISO DEL SISTEMA", 2);
                this.txtpuesto.requestFocus();
            } else {
                        //atentos, el sexo estÃ¡ con radio buttons
                     
                            ac.insertar(this.txtregistro.getText(), this.txtidarbitro.getText().toUpperCase(), this.txtidpartido.getText().toUpperCase(), this.txtpuesto.getText().toUpperCase());
                        JOptionPane.showMessageDialog(rootPane, "Registro guardado exitosamente!!", "AVISO DEL SISTEMA", 1);
                        Bloquear();
                        Limpiar();
                        this.txtregistro.setText("");
                        newRecord = false;
                   
                }
            
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed

        String codigo = JOptionPane.showInputDialog("Ingrese el codigo de Actor a buscar:");
        rs = ac.buscar(codigo);
        try {
            while (rs.next()) {
                this.txtregistro.setText(rs.getString(1));
                this.txtidarbitro.setText(rs.getString(2));
                this.txtidpartido.setText(rs.getString(3));
                this.txtpuesto.setText(rs.getString(4));
                
                prueba = true;
                registro = true;
                newRecord = false;
            }
            if (registro == false) {
                JOptionPane.showMessageDialog(rootPane, "Registro no encontrado!!!", "AVISO DEL SISTEMA", 0);
                //this.txtCodigo.setText("");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "AVISO DEL SISTEMA", 0);
        }
        registro = false;
        Bloquear();
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed

        if (prueba == true) {
            String codigo = this.txtregistro.getText();
            if (JOptionPane.showConfirmDialog(rootPane, "¿Desea eliminar el registro buscado?") == 0) {
                ac.eliminar(codigo);
                JOptionPane.showMessageDialog(rootPane, "Registro eliminado exitosamente!!", "AVISO DEL SISTEMA", 1);
                Bloquear();
                Limpiar();
                this.txtregistro.setText("");
                this.btnnuevo.setVisible(true);
                this.btnguardar.setVisible(true);
                prueba = false;
            }
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        if (prueba == true) {
            Desbloquear();
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btnguardarmodificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarmodificacionActionPerformed
        if (prueba == true) {
            if (this.txtregistro.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe existir un codigo de registro", "AVISO DEL SISTEMA", 2);
            } else if (this.txtidarbitro.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe llenar el campo ID ARBITRO", "AVISO DEL SISTEMA", 2);
                this.txtidarbitro.requestFocus();
            } else if (this.txtidpartido.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe llenar el campo ID PARTIDO", "AVISO DEL SISTEMA", 2);
                this.txtidpartido.requestFocus();
            } else if (this.txtpuesto.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe llenar el campo PUESTO", "AVISO DEL SISTEMA", 2);
                this.txtpuesto.requestFocus();
            }else {
                            ac.modificar(this.txtregistro.getText(), this.txtidarbitro.getText().toUpperCase(), this.txtidpartido.getText().toUpperCase(), this.txtpuesto.getText().toUpperCase());
                        JOptionPane.showMessageDialog(rootPane, "El registro ha sido correctamente actualizado!!", "AVISO DEL SISTEMA", 1);
                        Bloquear();
                        Limpiar();
                        this.txtregistro.setText("");
                        prueba= false;
                        newRecord = false;
                    
                }
            
        }
    }//GEN-LAST:event_btnguardarmodificacionActionPerformed

    private void txtidarbitroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidarbitroKeyTyped
         char val=evt.getKeyChar();
        if(Character.isLetter(val)){
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_txtidarbitroKeyTyped

    private void txtidpartidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidpartidoKeyTyped
        char val=evt.getKeyChar();
        if(Character.isLetter(val)){
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_txtidpartidoKeyTyped

    private void txtpuestoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpuestoKeyTyped
        char val=evt.getKeyChar();
        if(Character.isDigit(val)){
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_txtpuestoKeyTyped

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        txtregistro.setText("");
        txtidarbitro.setText("");
        txtidpartido.setText("");
        txtpuesto.setText("");
        Bloquear();
    }//GEN-LAST:event_btncancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmarbitros_partidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmarbitros_partidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmarbitros_partidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmarbitros_partidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmarbitros_partidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnguardarmodificacion;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JLabel lblidarbitro;
    private javax.swing.JLabel lblidpartido;
    private javax.swing.JLabel lblpuesto;
    private javax.swing.JLabel lblregistro;
    private javax.swing.JTextField txtidarbitro;
    private javax.swing.JTextField txtidpartido;
    private javax.swing.JTextField txtpuesto;
    private javax.swing.JTextField txtregistro;
    // End of variables declaration//GEN-END:variables
}
