/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemafutbol;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author H ERICK
 */
public class frmhechos extends javax.swing.JFrame {

    ResultSet rs = null;
    hechos ac = new hechos(); 
    boolean registro = false;
    boolean prueba = false;
    boolean newRecord = false;
    int cantidad = 0;
    int mayor = 0;
    public frmhechos() {
        initComponents();
        setLocationRelativeTo(null);
         txtidhecho.setEnabled(false);
        txtidtipo.setEnabled(false);
        txtidpartido.setEnabled(false);
        txtcarnet.setEnabled(false);
        txtminuto.setEnabled(false);
    }
private void Bloquear(){
        txtidhecho.setEnabled(false);
        txtidtipo.setEnabled(false);
        txtidpartido.setEnabled(false);
        txtcarnet.setEnabled(false);
        txtminuto.setEnabled(false);
        }
        
        private void Desbloquear() {
       txtidtipo.setEnabled(true);
       txtidpartido.setEnabled(true);
       txtcarnet.setEnabled(true);
       txtminuto.setEnabled(true);
       }
        
        private void Limpiar() {
       txtidtipo.setText("");
       txtidpartido.setText("");
       txtcarnet.setText("");
       txtminuto.setText("");
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblidhecho = new javax.swing.JLabel();
        txtidhecho = new javax.swing.JTextField();
        lblidtipo = new javax.swing.JLabel();
        txtidtipo = new javax.swing.JTextField();
        lblidpartido = new javax.swing.JLabel();
        txtidpartido = new javax.swing.JTextField();
        lblcarnet = new javax.swing.JLabel();
        lblminuto = new javax.swing.JLabel();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnguardarmodificacion = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        txtminuto = new javax.swing.JTextField();
        btnmenu2 = new javax.swing.JButton();
        txtcarnet = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HECHOS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblidhecho.setText("ID HECHO:");
        getContentPane().add(lblidhecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        getContentPane().add(txtidhecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 70, -1));

        lblidtipo.setText("ID TIPO:");
        getContentPane().add(lblidtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtidtipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidtipoKeyTyped(evt);
            }
        });
        getContentPane().add(txtidtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 130, -1));

        lblidpartido.setText("ID PARTIDO:");
        getContentPane().add(lblidpartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));

        txtidpartido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidpartidoKeyTyped(evt);
            }
        });
        getContentPane().add(txtidpartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 130, -1));

        lblcarnet.setText("CARNET:");
        getContentPane().add(lblcarnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lblminuto.setText("MINUTO:");
        getContentPane().add(lblminuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        btnnuevo.setText("NUEVO");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, -1));

        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        btnbuscar.setText("BUSCAR");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 120, -1));

        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        btnmodificar.setText("MODIFICAR");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        btnguardarmodificacion.setText("GUARDAR MODIFICACIÓN");
        btnguardarmodificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarmodificacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardarmodificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 190, -1));

        btncancelar.setText("CANCELAR");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 90, -1));

        txtminuto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtminutoKeyTyped(evt);
            }
        });
        getContentPane().add(txtminuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 130, -1));

        btnmenu2.setText("REGRESAR");
        btnmenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenu2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnmenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 130, -1));

        try {
            txtcarnet.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtcarnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidtipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidtipoKeyTyped
        char val=evt.getKeyChar();
        if(Character.isLetter(val)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtidtipoKeyTyped

    private void txtidpartidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidpartidoKeyTyped
        char val=evt.getKeyChar();
        if(Character.isLetter(val)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtidpartidoKeyTyped

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed

        // TODO add your handling code here:
        rs = null;
        //mÃ©todo en clase Clientes
        rs = ac.contarRegistros();
        try {
            while (rs.next()) {
                cantidad = rs.getInt(1);
                if (cantidad != 0) {
                    rs = null;
                    //mÃ©todo en clase Clientes
                    rs = ac.mayorRegistro();
                    while (rs.next()) {
                        mayor = rs.getInt(1) + 1;
                        //recuerde que debe completar 5 digitos
                        if (mayor < 10) {
                            txtidhecho.setText("0000" + mayor);
                        } else if (mayor < 100) {
                            this.txtidhecho.setText("000" + mayor);
                        } else if (mayor < 1000) {
                            txtidhecho.setText("00" + mayor);
                        } else if (mayor < 10000) {
                            txtidhecho.setText("0" + mayor);
                        } else {
                            txtidhecho.setText("" + mayor);
                        }
                    }
                } else {
                    txtidhecho.setText("0000"+1);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "AVISO DEL SISTEMA", 0);
        }
        Desbloquear();
        Limpiar();
        this.txtidtipo.requestFocus();
        newRecord = true;
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed

        if (newRecord == true) {
            if (this.txtidhecho.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe existir un codigo de hecho", "AVISO DEL SISTEMA", 2);
            } else if (this.txtidtipo.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe llenar el campo id tipo", "AVISO DEL SISTEMA", 2);
                this.txtidtipo.requestFocus();
            }else if (this.txtidpartido.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe llenar el campo id partido", "AVISO DEL SISTEMA", 2);
                this.txtidpartido.requestFocus();
            }else if (this.txtcarnet.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe llenar el campo carnet", "AVISO DEL SISTEMA", 2);
                this.txtcarnet.requestFocus();
            } else if (this.txtminuto.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe llenar el campo minuto!!", "AVISO DEL SISTEMA", 2);
                this.txtminuto.requestFocus();
            }else {

                    ac.insertar(this.txtidhecho.getText(), this.txtidtipo.getText().toUpperCase(), this.txtidpartido.getText().toUpperCase(), this.txtcarnet.getText().toUpperCase(), this.txtminuto.getText());
                    JOptionPane.showMessageDialog(rootPane, "Registro guardado exitosamente!!", "AVISO DEL SISTEMA", 1);
                    Bloquear();
                    Limpiar();
                    this.txtidhecho.setText("");
                    newRecord = false;

                }
            
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed

        String codigo = JOptionPane.showInputDialog("Ingrese el codigo de PARTIOD a buscar:");
        rs = ac.buscar(codigo);
        try {
            while (rs.next()) {
                this.txtidhecho.setText(rs.getString(1));
                this.txtidtipo.setText(rs.getString(2));
                this.txtidpartido.setText(rs.getString(3));
                this.txtcarnet.setText(rs.getString(4));
                this.txtminuto.setText(rs.getString(5));

                prueba = true;
                registro = true;
                newRecord = false;
            }
            if (registro == false) {
                JOptionPane.showMessageDialog(rootPane, "Registro no encontrado!!!", "AVISO DEL SISTEMA", 0);
                //this.txtCodigo.setText("");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "AVISO DEL SISTEMA", 0);
        }
        registro = false;
        Bloquear();
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed

        if (prueba == true) {
            String codigo = this.txtidhecho.getText();
            if (JOptionPane.showConfirmDialog(rootPane, "¿Desea eliminar el registro buscado?") == 0) {
                ac.eliminar(codigo);
                JOptionPane.showMessageDialog(rootPane, "Registro eliminado exitosamente!!", "AVISO DEL SISTEMA", 1);
                Bloquear();
                Limpiar();
                this.txtidhecho.setText("");
                this.btnnuevo.setVisible(true);
                this.btnguardar.setVisible(true);
                prueba = false;
            }
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        if (prueba == true) {
            Desbloquear();
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btnguardarmodificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarmodificacionActionPerformed
        if (prueba == true) {
            if (this.txtidhecho.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe existir un id hecho", "AVISO DEL SISTEMA", 2);
            } else if (this.txtidtipo.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe llenar el campo id tipo", "AVISO DEL SISTEMA", 2);
                this.txtidtipo.requestFocus();
            }else if (this.txtidpartido.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe llenar el campo id partido", "AVISO DEL SISTEMA", 2);
                this.txtidpartido.requestFocus();
            } else if (this.txtcarnet.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe llenar el campo carnet", "AVISO DEL SISTEMA", 2);
                this.txtcarnet.requestFocus();
            } else if (this.txtminuto.getText().equals(" ")) {
                JOptionPane.showMessageDialog(rootPane, "Debe llenar el campo minuto!!", "AVISO DEL SISTEMA", 2);
                this.txtminuto.requestFocus();
            }else {
                    ac.modificar(this.txtidhecho.getText(), this.txtidtipo.getText().toUpperCase(), this.txtidpartido.getText().toUpperCase(), this.txtcarnet.getText().toUpperCase(), this.txtminuto.getText());
                    JOptionPane.showMessageDialog(rootPane, "El registro ha sido correctamente actualizado!!", "AVISO DEL SISTEMA", 1);
                    Bloquear();
                    Limpiar();
                    this.txtidhecho.setText("");
                    prueba= false;
                    newRecord = false;

                }
            
        }
    }//GEN-LAST:event_btnguardarmodificacionActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        txtidhecho.setText("");
        txtidtipo.setText("");
        txtidpartido.setText("");
        txtcarnet.setText("");
        txtminuto.setText("");
        Bloquear();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void txtminutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtminutoKeyTyped
             char val=evt.getKeyChar();
        if(Character.isLetter(val)){
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_txtminutoKeyTyped

    private void btnmenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenu2ActionPerformed
        MENU ab = new MENU();
        ab.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnmenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmhechos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmhechos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmhechos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmhechos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmhechos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnguardarmodificacion;
    private javax.swing.JButton btnmenu2;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JLabel lblcarnet;
    private javax.swing.JLabel lblidhecho;
    private javax.swing.JLabel lblidpartido;
    private javax.swing.JLabel lblidtipo;
    private javax.swing.JLabel lblminuto;
    private javax.swing.JFormattedTextField txtcarnet;
    private javax.swing.JTextField txtidhecho;
    private javax.swing.JTextField txtidpartido;
    private javax.swing.JTextField txtidtipo;
    private javax.swing.JTextField txtminuto;
    // End of variables declaration//GEN-END:variables
}
